apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: template01-dev

labels:
- includeSelectors: true
  pairs:
    env: DEV

resources:
- ../../base/otel-collector
- ../../base/postgres

images:
- name: otel/opentelemetry-collector-contrib
  newTag: "0.142.0"
- name: postgres
  newTag: "18.1-trixie"
- name: prometheuscommunity/postgres-exporter
  newTag: "v0.18.1"
