apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
#- name: postgres-config
#  files:
#  - ./config/postgresql.conf
- name: postgres-init
  files:
  - ./init/00-createRoles.sql
  - ./init/01-createDatabase.sql
  - ./init/10-createCountry.sql
  - ./init/11-createExpenseCategory.sql
  - ./init/12-createExpense.sql

secretGenerator:
- name: postgres-secret
  literals:
  - username=postgres
  - password=admin


resources:
- persistentVolumeClaim.yaml
- statefulSet.yaml
- service.yaml
#- serviceAccount.yaml
