apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: postgres-init
  files:
  - ./init/00-createRoles.sql
  - ./init/01-createDatabase.sql
  - ./init/10-createCountry.sql
  - ./init/11-createCurrency.sql
  - ./init/12-createExpenseCategory.sql
  - ./init/13-createExpense.sql

secretGenerator:
- name: postgres-secrets
  literals:
  - username=postgres
  - password=admin
  #- exporter_username=
  #- exporter_password=


resources:
- persistentVolumeClaim.yaml
- statefulSet.yaml
- service.yaml
#- serviceAccount.yaml
