apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: otel-config
  files:
  - ./config/otel-config.yaml

resources:
- deployment.yaml
- service.yaml
- service-external.yaml #TODO: remove when Gateway API is setup


