apiVersion: v1
kind: Service

metadata:
  name: otel-collector-ext
  labels:
    app: otel-collector-ext

spec:
  selector:
    app: otel-collector
  type: NodePort
  ports:
  - name: metrics-external
    port: 18889
    targetPort: metrics2
    nodePort: 30889
    protocol: TCP
