apiVersion: v1
kind: Service

metadata:
  name: otel-collector
  labels:
    app: otel-collector

spec:
  selector:
    app: otel-collector
  ports:
  - name: grpc
    port: 4317
    targetPort: grpc
    protocol: TCP
  - name: http
    port: 4318
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 8888
    targetPort: metrics
    protocol: TCP
  - name: metrics2
    port: 8889
    targetPort: metrics2
    protocol: TCP
