apiVersion: v1
kind: Service

metadata:
  name: prometheus-external

spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: metrics-external
    port: 19090
    targetPort: metrics
    nodePort: 30909
    protocol: TCP
